[tool.poetry]
name = "skilswapbackend"
version = "0.1.0"
description = ""
authors = ["jonasstDev <jonas.strehler@t-online.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
